-- DROP DATABASE dbfumdesql;

-- MySQL Script generated by MySQL Workbench
-- Sat Oct 12 19:12:37 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbfumdesql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbfumdesql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbfumdesql` DEFAULT CHARACTER SET utf8 ;
USE `dbfumdesql` ;

-- -----------------------------------------------------
-- Table `dbfumdesql`.`tbUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfumdesql`.`tbUsuario` (
  `idUsuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(40) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(60) NOT NULL,
  `nivelPermissao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbfumdesql`.`tbAluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfumdesql`.`tbAluno` (
  `idAluno` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeAluno` VARCHAR(40) NOT NULL,
  `matriculaAluno` INT(11) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  `dataIngresso` DATE NOT NULL,
  `instituicao` VARCHAR(40) NOT NULL,
  `faseAtual` INT NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `idUsuario` INT(11) NOT NULL,
  PRIMARY KEY (`idAluno`),
  CONSTRAINT `fk_tbaluno_tbUsuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `dbfumdesql`.`tbUsuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbfumdesql`.`tbDocumentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfumdesql`.`tbDocumentos` (
  `idDocumentos` INT(11) NOT NULL AUTO_INCREMENT,
  `aluno_idAluno` INT(11) NOT NULL,
  `caminhoDocumento` VARCHAR(45) NOT NULL,
  `dataDocumento` DATETIME NOT NULL,
  `horasDocumento` INT NOT NULL,
  PRIMARY KEY (`idDocumentos`),
  CONSTRAINT `fk_documentos_aluno`
    FOREIGN KEY (`aluno_idAluno`)
    REFERENCES `dbfumdesql`.`tbAluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dbfumdesql`.`tbHoraspendentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbfumdesql`.`tbHoraspendentes` (
  `idHorasPendentes` INT(11) NOT NULL AUTO_INCREMENT,
  `semestre` ENUM('1', '2') NOT NULL,
  `ano` INT(11) NOT NULL,
  `quantidadePendente` INT(11) NOT NULL,
  `aluno_idAluno` INT(11) NOT NULL,
  PRIMARY KEY (`idHorasPendentes`),
  CONSTRAINT `fk_horasPendentes_aluno`
    FOREIGN KEY (`aluno_idAluno`)
    REFERENCES `dbfumdesql`.`tbAluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
